#WINDOWS
# source 'http://rubygems.org'
# gem 'rails', '4.2.5.1'
# gem 'pg', '~> 0.15'
# gem 'sass-rails', '~> 5.0'
# gem 'uglifier', '>= 1.3.0'
# gem 'coffee-rails', '~> 4.1.0'
# gem 'jquery-rails'
# gem 'turbolinks'
# gem 'jbuilder', '~> 2.0'
# gem 'bootstrap-sass'
# gem 'font-awesome-sass'
# gem 'sdoc', '~> 0.4.0', group: :doc
# gem 'simple_form'
# gem 'devise'
# gem 'has_scope'
# gem 'magnific-popup-rails', '~> 1.1.0'
# gem 'nokogiri', '1.7.1'
# gem 'tzinfo-data'

source 'https://rubygems.org'
gem 'rails', '4.2.5.1'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'simple_form'
gem 'devise'
gem 'has_scope'
gem 'magnific-popup-rails', '~> 1.1.0'
gem 'anjlab-bootstrap-rails', '~> 3.0.0.3', :require => 'bootstrap-rails'
