production:
  adapter: postgresql
  encoding: unicode
  database: r2
  pool: 5
  username: postgres
  password: diegoh6

development:
  adapter: postgresql
  encoding: unicode
  database: r2
  pool: 5
  username: postgres
  password: diegoh6
test:
  adapter: postgresql
  encoding: unicode
  database: r2
  pool: 5
  username: postgres
  password: diegoh6
  