production:
  adapter: postgresql
  encoding: unicode
  database: r2
  pool: 5
  username: postgres
  password: 120188

development:
  adapter: postgresql
  encoding: unicode
  database: r2
  pool: 5
  username: postgres
  password: 120188
test:
  adapter: postgresql
  encoding: unicode
  database: r2
  pool: 5
  username: postgres
  password: 120188
  